### ISSUE TITLE
Formating the response.

### ISSUE THREAD

**Issue by adhikareeprayush** [adhikareeprayush/GEMINI-CLONE#2]
While fetching the response from the API. We are getting an MD response, so I would love it if anyone could fix the texts so they are displayed correctly.
An example :
![image](https://github.com/user-attachments/assets/829e4ae3-b931-4b50-ada3-0bdbab642623)

**Comment by pranavraikar01** [comment]
Hey @adhikareeprayush I would like to solve this issue will you please elaborate what the issue is in detail. I am not able to get it correctly.

**Comment by pranavraikar01** [comment]
I have worked on the issue and tried to figure it out and solve it 
![image](https://github.com/user-attachments/assets/28e671f7-8f64-4d81-a979-6d9cc1b6d99d)
Is this the format of response you want ,if yes then please assign me this issue or else I can also raise a PR you please merge it in the project.
